var auto_cats = ["..", "Bikes",
"MUVs",
"Cars",
"Vans",
"Buses",
"Caravans",
"Trucks",
"Tractor Units",
"Public Utility",
"Trailers",
"Semitrailers",
"Construction Machinery",
"Agricultural Machinery",
"Industrial Machinery",
"Forklifts",
"Containers",
"Boats",
"Others"];